### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [BjoernIlling/Moyano_et_al_2022_Fig.2#1]
data = data %>% mutate(Year=as.numeric(Year),
                       GERAS.Age.1=as.numeric(GERAS.Age.1),
                       GERAS.Age.1_billions=as.numeric(GERAS.Age.1/1000),
                       GERAS_N20_comp_billions=as.numeric(GERAS_N20_comp/1000),
                       N20.Age.0=as.numeric(N20.Age.0),
                       N20.Age.0_billions=as.numeric(N20.Age.0/1000),
                       Low.Recruitment_billions=as.numeric(Low.Recruitment/1000000),
                       Recruitment_billions=as.numeric(Recruitment/1000000),
                       High.Recruitment_billions=as.numeric(High.Recruitment/1000000),
                       SSB_thousands=as.numeric(SSB/1000),
                       Low.SSB_thousands=as.numeric(Low.SSB/1000),
                       High.SSB_thousands=as.numeric(High.SSB/1000),
                       Catches_thousands=as.numeric(Catches/1000))

GERAS.Age.1_billions=as.numeric(GERAS.Age.1/1000),
                       GERAS_N20_comp_billions=as.numeric(GERAS_N20_comp/1000),N20.Age.0_billions=as.numeric(N20.Age.0/1000), 
are these billions or thousands|?

**Comment by BjoernIlling** [comment]
Thanks for the comment. The numbers for GERAS Age 1 and N20 Age 0 were originally provided in millions, hence the division by 1000 for obtaining billions.

**Comment by liamxg** [comment]
thanks. Very good materials.
